from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from .views import (
    HomeView,
    CompanyView,
    AuctionListView,
    AuctionView,
    CalculatorView,
    ContactView,
    AccountView,
    LoginView,
    RegisterView,
    ProfileView,
    LastAuctionsView,
    ObservedView,
    WonView,
    CurrenciesView,
    SearchView,
    AdsView,
    RulesView,
    EntryView,
    ChangePasswordView,
    UploadCenterView,
    DownloadCenterView,
    ShortUrlRedirectView,
    RemindPasswordView,
    FaqView,
)


urlpatterns = [
    url('^$', AuctionListView.as_view()),
    url('^home/$', HomeView.as_view()),
    url('^faq/$', FaqView.as_view()),
    url('^zaloguj/$', LoginView.as_view(), name='login'),
    url('^przypomnij/$', RemindPasswordView.as_view(), name='remind'),
    url('^przypomnij/(?P<token>[0-9a-z]+)/$', RemindPasswordView.as_view(), name='remind'),
    url('^wyloguj/$', auth_views.logout, {'next_page': '/aukcje'}, name='logout'),
    url('^zarejestruj/$', RegisterView.as_view(), name='register'),
    url('^home/$', HomeView.as_view()),
    url('^firma/$', CompanyView.as_view()),
    url('^aukcje/$', AuctionListView.as_view()),
    url('^aukcje/(?P<page>[0-9]+)/$', AuctionListView.as_view()),
    url('^aukcje/licytacja/(?P<pk>[0-9]+)/(?P<title>[\.\-a-z0-9]+)/$',
        AuctionView.as_view()),
    url('^kalkulator/$', CalculatorView.as_view()),
    url('^kontakt/$', ContactView.as_view()),
    url('^konto/$', LastAuctionsView.as_view()),
    url('^konto/profil/$', ProfileView.as_view()),
    url('^konto/licytacje/$', LastAuctionsView.as_view()),
    url('^konto/licytacje/(?P<page>[0-9]+)/$', LastAuctionsView.as_view()),
    url('^konto/obserwowane/$', ObservedView.as_view()),
    url('^konto/obserwowane/(?P<page>[0-9]+)/$', ObservedView.as_view()),
    url('^konto/wygrane/$', WonView.as_view()),
    url('^konto/wygrane/(?P<page>[0-9]+)/$', WonView.as_view()),
    url('^konto/poszukiwane/$', SearchView.as_view()),
    url('^konto/poszukiwane/(?P<page>[0-9]+)/$', SearchView.as_view()),
    url('^ogloszenia/$', AdsView.as_view()),
    url('^api/v1/currencies/$', CurrenciesView.as_view()),
    url('^zasady/$', RulesView.as_view()),
    url('^admin/rest_api/userprivate/add/$', RegisterView.as_view()),
    url('^konto/nowe_haslo/$', ChangePasswordView.as_view()),
    url('^konto/pliki/(?P<auction_id>[\-a-zA-Z0-9]+)/(?P<file_id>[0-9]+)/$', UploadCenterView.as_view()),
    url('^konto/pliki/(?P<auction_id>[\-a-zA-Z0-9]+)/$', UploadCenterView.as_view()),
    url('^panel/potwierdzenia/szukaj/$', DownloadCenterView.as_view()),
    url('^panel/potwierdzenia/(?P<page_id>[0-9]+)/$', DownloadCenterView.as_view()),
    url('^panel/potwierdzenia/$', DownloadCenterView.as_view()),
    url('^_(?P<short_url>[a-zA-Z]+)/$', ShortUrlRedirectView.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)